# Generated by Django 4.0.5 on 2022-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frendo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslogin',
            name='user_img',
            field=models.ImageField(default=1, upload_to='frendo/images'),
            preserve_default=False,
        ),
    ]
